name: Build & Test (PHP 8.2)
env:
  TESTING_ENV: ${{ secrets.TESTING_ENV }}

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
          if: success()

      -   name: Setup PHP with coverage driver
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            coverage: pcov

      -   name: Setup
          if: success()
          run: |
            php -v
            composer install --no-interaction
            echo "$TESTING_ENV" > .env
            echo "$TESTING_ENV" > .env.testing
            php artisan key:generate
            php artisan key:generate --env=testing
            php artisan optimize
            touch database/database.sqlite

      -   name: PHPUnit tests with coverage
          if: success()
          run: |
            composer test-coverage

      -   name: upload coverage to codecov.io
          if: success()
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            file: ./coverage.xml
